### ISSUE TITLE
Getting "'main' panicked at 'already borrowed: BorrowMutError'"

### ISSUE THREAD

**Issue by gage117** [denjucks/snelm#2]
I was attempting to import this middleware with Oak but couldn't get it to behave with the code I had, so I tried making a test file that was an exact copy of the Oak example you have in the documentation but even that kept giving me the 'main' panicked at 'already borrowed: BorrowMutError' error. 

EDIT: Wanted to add that commenting out the app.use(...) part of the code still results in the error, commenting out 'await snelm.init()' results in the error no longer being there but it is if I leave it uncommented. I believe the error is resulting from snelm.init()?

This is the code I'm using:
```import { Application } from "https://deno.land/x/oak/mod.ts";
import { Snelm } from "https://deno.land/x/snelm/mod.ts";

const app = new Application();

// Configuring Snelm for the Oak framework
const snelm = new Snelm("oak");
await snelm.init();

// Snelm Middleware for Oak
app.use((ctx, next) => {
    ctx.response = snelm.snelm(ctx.request, ctx.response);

    next();
});

app.use((ctx) => {
    ctx.response.body = "Oak";
});

export { app }
```
And this is the error I receive:
```
thread 'main' panicked at 'already borrowed: BorrowMutError', /rustc/4fb7144ed159f94491249e86d5bbd033b5d60550\src\libcore\cell.rs:878:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

This is my first time trying out a project in Deno and using these packages so apologies if the solution is obvious.

**Comment by denjucks** [comment]
Looks like it is an issue with newer versions of Deno. Try running `deno upgrade` and let me know if the issue persists

**Comment by gage117** [comment]
Running `deno upgrade` fixed the issue! Thank you for the quick response!
